 

site_name: Guia Bolso
site_description: Repositório da disciplina de Requisitos 2019.1
repo_url: https://github.com/ebmm01/Requisitos-2019.1
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/ebmm01/Requisitos-2019.1/">Requisitos 2019.1</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  palette:
    primary: 'white'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ebmm01/Requisitos-2019.1'

plugins:
  - search
  - awesome-pages
